#!/bin/bash
set -eu -o pipefail

. "$(dirname "$0")"/_common

openqa_url=${openqa_url:-https://openqa.opensuse.org}
distri=${distri:-opensuse}
flavor=${flavor:-DVD}
flavor_override=${flavor_override:-mm-monitoring} # override flavor to avoid obsoletion by other scheduled products
arch=${arch:-x86_64}
version=${version:-Tumbleweed}
test_name=${test_name:-ping_client}
# we expect build numbers in the ISO 8601 format so we're looking for build strings starting with eight latin numerals
build_regex=${build_regex:-^[0-9]+$}
machine=${machine:-uefi}

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

cat > "$tmpfile" << EOF
---
products:
  mm-ping-test:
    distri: $distri
    flavor: $flavor_override
    arch: $arch
    version: $version

machines:
  ${machine}:
    backend: qemu
    settings:
      WORKER_CLASS: qemu_x86_64,tap

.common: &common
  BOOT_HDD_IMAGE: '1'
  DESKTOP: textmode
  IS_MM_SERVER: '1'
  NICTYPE: tap
  EXPECTED_NM_CONNECTIVITY: '(limited|full)'
  QEMU_DISABLE_SNAPSHOTS: '1'
  YAML_SCHEDULE: schedule/functional/mm_ping.yaml

job_templates:
  ping_server:
    product: mm-ping-test
    machine: $machine
    settings:
      <<: *common
      HOSTNAME: server
  ping_client:
    product: mm-ping-test
    machine: $machine
    settings:
      <<: *common
      HOSTNAME: client
      PARALLEL_WITH: ping_server
EOF

usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Schedules openQA multi-machine "ping tests". Used in CI monitoring jobs.

Can be configured additionally with environment variables.

Options:
 -h, --help         display this help
EOF
    exit "$1"
}

main() {
    opts=$(getopt -o h -l help -n "$0" -- "$@") || usage 1
    eval set -- "$opts"
    while true; do
        case "$1" in
            -h | --help) usage 0 ;;
            --)
                shift
                break
                ;;
            *) break ;;
        esac
    done
    jobdata=$(runcli openqa-cli api --host "$openqa_url" jobs version="$version" scope=relevant arch="$arch" machine="$machine" flavor="$flavor" test="$test_name" latest=1)
    # shellcheck disable=SC2016 # not expanding the filter is deliberate
    jobdata_newest=$(runjq -r --arg regex "$build_regex" '.jobs | map(select(.result == "passed")) | map(select (.settings.BUILD | match($regex))) | max_by(.settings.BUILD)' <<< "$jobdata")
    # shellcheck disable=SC2016
    hdd=$(runjq -r --arg regex "$build_regex" '.settings.HDD_1' <<< "$jobdata_newest")
    # shellcheck disable=SC2016
    pflash_code=$(runjq -r --arg regex "$build_regex" '.settings.UEFI_PFLASH_CODE' <<< "$jobdata_newest")
    # shellcheck disable=SC2016
    pflash_vars=$(runjq -r --arg regex "$build_regex" '.settings.UEFI_PFLASH_VARS' <<< "$jobdata_newest")
    time openqa-cli schedule \
        --monitor --follow \
        --host "$openqa_url" \
        --param-file SCENARIO_DEFINITIONS_YAML="$tmpfile" \
        DISTRI="$distri" VERSION="$version" FLAVOR="$flavor_override" ARCH="$arch" \
        BUILD="$(date -Im)" _GROUP_ID=0 \
        UEFI=1 \
        UEFI_PFLASH_CODE="$pflash_code" \
        UEFI_PFLASH_VARS="$pflash_vars" \
        HDD_1="$hdd"
}

caller 0 > /dev/null || main "$@"
