#!/bin/bash -e

set -o pipefail -o errtrace

to_review=()

print_summary() {
    local to_review_count=${#to_review[@]}
    [[ $to_review_count -eq 0 ]] && return
    local msg="\n\e[1m\e[31m$to_review_count unknown issues to be reviewed:\e[0m"
    for job in "${to_review[@]}"; do
        msg+="\n - $job"
    done
    echo -e "$msg"
}

main() {
    opts=$(getopt -o h -l help -n "$0" -- "$@") || usage 1
    eval set -- "$opts"
    while true; do
        case "$1" in
            -h | --help) usage 0 ;;
            --)
                shift
                break
                ;;
            *) break ;;
        esac
    done

    # shellcheck disable=SC2013
    for testurl in $(cat - | sed 's/ .*$//'); do
        err_out=$(mktemp)
        set +e
        { "$(dirname "$0")"/openqa-label-known-issues "$testurl" 2>&1 1>&3 | tee "$err_out" >&2; } 3>&1
        rc=${PIPESTATUS[0]}
        set -e
        if [[ $rc -ne 0 ]]; then
            rm -f "$err_out"
            exit "$rc"
        fi
        if grep -q "Unknown test issue, to be reviewed" "$err_out"; then
            to_review+=("$testurl")
        fi
        rm -f "$err_out"
    done
    print_summary
}

usage() {
    cat << EOF
Usage: printf "url1\nurl2\n" | $0 [OPTIONS]

Calls 'openqa-label-known-issues' on one or more openQA job URLs provided via
standard input.

Options:
 -h, --help         display this help
EOF
    exit "$1"
}

caller 0 > /dev/null || main "$@"
